module.exports = {
    LOGIN_API: "LOGIN_API",
    USER_REGISTER_API: "USER_REGISTER_API",
    FORGOT_PASSWORD_API: "FORGOT_PASSWORD_API",
    SEND_COORDINATE_API: "SEND_COORDINATE_API",
    ADD_FARM_API: 'ADD_FARM_API',
    GET_ALL_FARM_API: 'GET_ALL_FARM_API',
    USER_LOGGED: "USER_LOGGED",
    SHOW_MODAL: "SHOW_MODAL",
    SHOW_PROGRESS: "SHOW_PROGRESS",
    GET_GRAPH_DATA_API: "GET_GRAPH_DATA_API"
}